name: bh_aerial_image_1999
description: Aerial imagem of Belo Horizonte - Minas Gerais - Brazil - 1999 
metadata_type: eo3

license: CC-BY-4.0

metadata:
  product:
    name: bh_aerial_image_1999

storage:
    crs: EPSG:29193
    resolution:
      x: 0.399711
      y: -0.399711

measurements:
  - name: red
    dtype: "uint8"
    units: "1"
    nodata: -1

  - name: green
    dtype: "uint8"
    units: "1"
    nodata: -1

  - name: blue
    dtype: "uint8"
    units: "1"
    nodata: -1