name: bh_aerial_image_1999_modified
description: Aerial image of Belo Horizonte - Minas Gerais - Brazil - 1999. Modified resolution version.
metadata_type: eo3

license: CC-BY-4.0

metadata:
  product:
    name: bh_aerial_image_1999_modified

storage:
    crs: EPSG:29193
    resolution:
      x: 0.2797973  # 70% of 0.399711
      y: -0.2797973 # 70% of -0.399711

measurements:
  - name: red
    dtype: "uint8"
    units: "1"
    nodata: 0

  - name: green
    dtype: "uint8"
    units: "1"
    nodata: 0

  - name: blue
    dtype: "uint8"
    units: "1"
    nodata: 0
